export const siteConfig = {
  name: 'Zane Shi',
  domain: 'zaneshi.com',
  url: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://h5.zaneshi.com',
  description: 'Zane Shi 的个人网站，记录技术、AI、生活、摄影、骑行与滑雪。',
  nav: [
    { title: 'Home', href: '/' },
    { title: 'About', href: '/about' },
    { title: 'Blog', href: '/blog' },
    { title: 'Projects', href: '/projects' },
    { title: 'Life', href: '/life' },
    { title: 'AI', href: '/ai' },
    { title: 'Travel', href: '/travel' },
    { title: 'Career', href: '/career' },
    { title: 'Tutorial', href: '/tutorial' },
    { title: 'Client', href: '/client' },
    { title: 'Tools', href: '/tools' },
    { title: 'Contact', href: '/contact' },
  ],
} as const;
